version: '3'

services:
  chatbot-db:
    image: postgres:16.2
    container_name: chatbot-db
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: simsim
      POSTGRES_PASSWORD: simsim
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
